package database;
// Generated 17 Jan, 2024 7:28:57 PM by Hibernate Tools 4.3.1



/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private int id;
     private String name;
     private Integer age;
     private String phone;

    public Person() {
    }

	
    public Person(int id) {
        this.id = id;
    }
    public Person(int id, String name, Integer age, String phone) {
       this.id = id;
       this.name = name;
       this.age = age;
       this.phone = phone;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }




}


